server:
  port: 0
  error:
    include-message: always
spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: root
      password: password
      database: product-service
      port: 27017
      host: localhost
  application:
    name: product-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG